name: 🚀 Deploy EV Service Portal (rider + admin)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    working-directory: site

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm install

      - name: 🏗️ Build Vite project
        run: npm run build

      - name: 📂 Copy /admin folder manually into dist
        run: |
          mkdir -p ./site/dist/admin
          cp -r ./site/public/admin/* ./site/dist/admin/

      - name: 🚀 Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site/dist
          force_orphan: true
